version: '2'

services:
  proxy:
    build: ./
    ports:
      - 8086:8086
      - 8087:8087
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
networks:
    vpcbr:
        driver: bridge
        ipam:
          config:
            - subnet: 10.5.0.0/16
              gateway: 10.5.0.1
